# Generated by Django 4.1.7 on 2023-03-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_location_alter_house_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
