# Generated by Django 4.1.7 on 2023-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_booking_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='houses.amenity'),
        ),
    ]
