# Generated by Django 4.1.7 on 2023-03-19 15:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_alter_house_image1_alter_house_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 550], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 550], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 550], upload_to='images/'),
        ),
    ]
