# Generated by Django 4.1.7 on 2023-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Phones and Tablets', 'Phones and Tablets'), ('Laptops', 'Laptops'), ('Accessories', 'Accessories'), ('Skin Care', 'Skin Care'), ('Hair Products', 'Hair Products'), ('Fragrances', 'Fragrances'), ('Food', 'Food'), ('Beauty and Cosmetics', 'Beauty and Cosmetics'), ('Other', 'Other')], max_length=50),
        ),
    ]
