# Generated by Django 4.1.7 on 2023-03-19 15:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 600], upload_to='images/'),
        ),
    ]
