# Generated by Django 4.1.7 on 2023-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
